# Generated by Django 4.2.5 on 2023-12-19 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_coxed', models.BooleanField(default=True)),
                ('n_rowers', models.IntegerField(default=8)),
                ('is_port_stroke', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('grad_year', models.IntegerField(default=9999)),
                ('is_port', models.BooleanField(default=False)),
                ('is_starboard', models.BooleanField(default=False)),
                ('is_rookie', models.BooleanField(default=True)),
                ('total_minutes', models.IntegerField(default=0)),
                ('total_absences', models.IntegerField(default=0)),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oars', models.CharField(max_length=50)),
                ('is_port_stroke', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_coached', to='central.user')),
                ('coxswain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_coxed', to='central.user')),
                ('launch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats_launched', to='central.user')),
                ('rowers', models.ManyToManyField(blank=True, to='central.user')),
                ('shell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='central.shell')),
            ],
        ),
        migrations.CreateModel(
            name='Extra_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('minutes', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_workouts', to='central.user')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('reason', models.CharField(max_length=200)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='central.user')),
            ],
        ),
    ]
